### ISSUE TITLE
Default migration crashing

### ISSUE THREAD

**Issue by GuillaumeValadas** [SecTheater/artify#1]
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.01 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.01 seconds)
Migrating: 2017_11_21_171555_artify_roles_tables

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1005 Can't create table `common`.`role_users` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `role_users` add constraint `role_users_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)

**Comment by GuillaumeValadas** [comment]
Exception trace:

  1   PDOException::("SQLSTATE[HY000]: General error: 1005 Can't create table `common`.`role_users` (errno: 150 "Foreign key constraint is incorrectly formed")")
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

**Comment by secmohammed** [comment]
Thanks @YouzOnline , It should be fixed now
[fixed on commit](https://github.com/SecTheater/artify/commit/e97725db0147c9784214a33336d362ecf49db6ec) [and this commit](https://github.com/SecTheater/artify/commit/b0f025f8d9addccddf3218a96b4111f8fc16848e)

please try again, and follow up if there's something wrong.
