### ISSUE TITLE
Laravel 5.8 tenant connection migration issue.

### ISSUE THREAD

**Issue by shahzad-sarwar** [SecTheater/artify#2]
I am following the tutorial on medium about multi-tenancy, when I ran art:migrate it give a foreign key error.

SQLSTATE[HY000]: General error: 1005 Can't create table `multi-tenant`.`tenant_connections` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `tenant_connections` add constraint `tenant_connections_tenant_id_foreign` foreign key (`tenant_id`) references `companies` (`id`))

Any help would be appreciated.

**Comment by secmohammed** [comment]
can you show me the company migration file?, and tenant connections if possible.

**Comment by shahzad-sarwar** [comment]
Thank you for your response.

Here is tenant_connections migration

` 
Schema::create('tenant_connections', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('tenant_id');
            $table->string('database');
            $table->timestamps();
            if (config('artify.tenant') && app(config('artify.tenant'))) {
                $table->foreign('tenant_id')->references('id')->on(str_plural(app(config('artify.tenant'))->getTable()));
            }});
`


Company Migration

` Schema::create('companies', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->unsignedBigInteger('user_id');
            $table->foreign('user_id')->references('id')->on('users');
            $table->timestamps();
        });`

**Comment by secmohammed** [comment]
sorry for the late response, but I think that your migrations aren't sorted correctly which means you can't migrate the tenant connections as it's searching for companies which isn't created yet. perhaps you should alter the date of the company migration to make it migrate first before the tenant connection so it can reference, or you can delete this line 
 
```
if (config('artify.tenant') && app(config('artify.tenant'))) { 
    $table->foreign('tenant_id')->references('id')->on(
                  str_plural(app(config('artify.tenant'))->getTable()
            )
    ); 
}
```

**Comment by shahzad-sarwar** [comment]
Hello thank you again for your response I changed the migration date and it's migrated, when i tried to create the company, it was giving an error of the uuid field in the companies table, i added it as well.

tenant_connections table has laravel_1 database. Though no database was created, I'm using laradock, with nginx and mariadb.

When i tried php artisan tenants:migrate it gives an error. 

 Unknown database 'laravel_1' (SQL: select * from information_schema.tables where table_schema = laravel_1 and table_name = migrations and table_type = 'BASE TABLE')

Can you please help me out?

**Comment by secmohammed** [comment]
have you specified the tenant model at your config?, because the migration command for tenants checks on the tenant model, then it checks on if the database exists or not, if it doesn't exist it will create it for you.

**Comment by secmohammed** [comment]
I would appreciate if you tell me the workflow you followed, as it should create the database automatically for you, so I can debug what went wrong and do a quick fix.
for the time being, if you want to fix it asap, just run the following command to create this database.

```
php artisan artify:db "name of your database" "name of the driver"
```

**Comment by shahzad-sarwar** [comment]
this is my artify.php file.

` return [
  'is_adr' => false,
  'is_multi_tenancy' => true,
  'tenant' => 'App\\Company',
  'cache' => 
  [
    'enabled' => false,
    'duration' => 10,
  ],
];`

I have created the tenants database from the above command, but when I fetch data as shown in the tutuorial it gives an error of  "message": "Database [tenant] not configured.",

**Comment by secmohammed** [comment]
sorry for the late response, all you have to do is register the event and listener for creating tenants at your service provider.

        TenantIdentified::class => [
            RegisterTenant::class,
        ],
